# Generated by Django 4.2.4 on 2023-08-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='url',
            field=models.CharField(default='https://www.open.spotify.com', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
