# Generated by Django 4.2.5 on 2023-09-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='avg_acousticness',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='avg_danceability',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='avg_duration',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='avg_energy',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='avg_loudness',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='avg_tempo',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='avg_valence',
        ),
    ]
