name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    


jobs:
  build:
  
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      DJANGO_SETTINGS_MODULE: playlist_analyser.settings
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Code Linting
      working-directory: playlist_analyser/
      run: |
        flake8
    - name: Run Tests and generate coverage
      working-directory: playlist_analyser/
      run: |
        pytest --cov=playlist_analysis --cov-report=json

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with: 
        directory: ./playlist_analyser/
