name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  name: Pipeline

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Code Linting
      working-directory: playlist_analyser/
      run: |
        flake8
    - name: Run Tests
      working-directory: playlist_analyser/
      run: |
        export DJANGO_SETTINGS_MODULE=playlist_analyser.settings
        echo $CLIENT_ID
        pytest
        pytest --cov
