name: React

on:
  push:
    branches: ["main", "Pipeline", "Frontend"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: frontend/
        run: npm install

      - name: Build React App
        working-directory: frontend/
        run: npm run build
      
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ubuntu
          TARGET: /home/ubuntu/frontend/build
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          rsync -rav -e "ssh -i ~/.ssh/id_rsa" frontend/build $USERNAME@$HOST:$TARGET
          rm -rf ~/.ssh/id_rsa

  lint:
    # needs: common
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: frontend/
        run: npm install

      - name: Run ESLint
        working-directory: frontend/
        run: npm run lint
