name: React

on:
  push:
    branches: ["main", "Pipeline", "Frontend"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: frontend/
        run: npm install

      - name: Build React App
        working-directory: frontend/
        run: npm run build

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH }}

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ubuntu
          TARGET: /home/ubuntu/frontend/build
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          rsync -rav -e "ssh" frontend/build $USERNAME@$HOST:$TARGET

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: frontend/
        run: npm install

      - name: Run ESLint
        working-directory: frontend/
        run: npm run lint
