name: React

on:
  push:
    branches:
      - main
      - Pipeline
  pull_request:
    branches:
      - main
      - Pipeline

jobs:
  common:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies with npm ci
        run: |
          npm install

  build:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build React App
        working-directory: frontend/
        run: npm run build


  lint:
    needs: common
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ESLint
        working-directory: frontend/
        run: npm run lint
